# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/smutekj/Desktop/Renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/smutekj/Desktop/Renderer/build-web

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/smutekj/Desktop/Renderer/build-web/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"headers\" \"pkgconfig\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smutekj/Desktop/Renderer/build-web/CMakeFiles /home/smutekj/Desktop/Renderer/build-web//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smutekj/Desktop/Renderer/build-web/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named renderer

# Build rule for target.
renderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 renderer
.PHONY : renderer

# fast build rule for target.
renderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/build
.PHONY : renderer/fast

#=============================================================================
# Target rules for targets named Example

# Build rule for target.
Example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Example
.PHONY : Example

# fast build rule for target.
Example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/build
.PHONY : Example/fast

#=============================================================================
# Target rules for targets named freetype

# Build rule for target.
freetype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 freetype
.PHONY : freetype

# fast build rule for target.
freetype/fast:
	$(MAKE) $(MAKESILENT) -f external/freetype/CMakeFiles/freetype.dir/build.make external/freetype/CMakeFiles/freetype.dir/build
.PHONY : freetype/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

src/Batch.o: src/Batch.cpp.o
.PHONY : src/Batch.o

# target to build an object file
src/Batch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Batch.cpp.o
.PHONY : src/Batch.cpp.o

src/Batch.i: src/Batch.cpp.i
.PHONY : src/Batch.i

# target to preprocess a source file
src/Batch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Batch.cpp.i
.PHONY : src/Batch.cpp.i

src/Batch.s: src/Batch.cpp.s
.PHONY : src/Batch.s

# target to generate assembly for a file
src/Batch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Batch.cpp.s
.PHONY : src/Batch.cpp.s

src/Example/Application.o: src/Example/Application.cpp.o
.PHONY : src/Example/Application.o

# target to build an object file
src/Example/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/Application.cpp.o
.PHONY : src/Example/Application.cpp.o

src/Example/Application.i: src/Example/Application.cpp.i
.PHONY : src/Example/Application.i

# target to preprocess a source file
src/Example/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/Application.cpp.i
.PHONY : src/Example/Application.cpp.i

src/Example/Application.s: src/Example/Application.cpp.s
.PHONY : src/Example/Application.s

# target to generate assembly for a file
src/Example/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/Application.cpp.s
.PHONY : src/Example/Application.cpp.s

src/Example/ShaderUI.o: src/Example/ShaderUI.cpp.o
.PHONY : src/Example/ShaderUI.o

# target to build an object file
src/Example/ShaderUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/ShaderUI.cpp.o
.PHONY : src/Example/ShaderUI.cpp.o

src/Example/ShaderUI.i: src/Example/ShaderUI.cpp.i
.PHONY : src/Example/ShaderUI.i

# target to preprocess a source file
src/Example/ShaderUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/ShaderUI.cpp.i
.PHONY : src/Example/ShaderUI.cpp.i

src/Example/ShaderUI.s: src/Example/ShaderUI.cpp.s
.PHONY : src/Example/ShaderUI.s

# target to generate assembly for a file
src/Example/ShaderUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/ShaderUI.cpp.s
.PHONY : src/Example/ShaderUI.cpp.s

src/Example/main.o: src/Example/main.cpp.o
.PHONY : src/Example/main.o

# target to build an object file
src/Example/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/main.cpp.o
.PHONY : src/Example/main.cpp.o

src/Example/main.i: src/Example/main.cpp.i
.PHONY : src/Example/main.i

# target to preprocess a source file
src/Example/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/main.cpp.i
.PHONY : src/Example/main.cpp.i

src/Example/main.s: src/Example/main.cpp.s
.PHONY : src/Example/main.s

# target to generate assembly for a file
src/Example/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Example.dir/build.make CMakeFiles/Example.dir/src/Example/main.cpp.s
.PHONY : src/Example/main.cpp.s

src/Font.o: src/Font.cpp.o
.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i
.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s
.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/FrameBuffer.o: src/FrameBuffer.cpp.o
.PHONY : src/FrameBuffer.o

# target to build an object file
src/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/FrameBuffer.cpp.o
.PHONY : src/FrameBuffer.cpp.o

src/FrameBuffer.i: src/FrameBuffer.cpp.i
.PHONY : src/FrameBuffer.i

# target to preprocess a source file
src/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/FrameBuffer.cpp.i
.PHONY : src/FrameBuffer.cpp.i

src/FrameBuffer.s: src/FrameBuffer.cpp.s
.PHONY : src/FrameBuffer.s

# target to generate assembly for a file
src/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/FrameBuffer.cpp.s
.PHONY : src/FrameBuffer.cpp.s

src/Gui/backends/imgui_impl_opengl3.o: src/Gui/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/Gui/backends/imgui_impl_opengl3.o

# target to build an object file
src/Gui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_opengl3.cpp.o
.PHONY : src/Gui/backends/imgui_impl_opengl3.cpp.o

src/Gui/backends/imgui_impl_opengl3.i: src/Gui/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/Gui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
src/Gui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_opengl3.cpp.i
.PHONY : src/Gui/backends/imgui_impl_opengl3.cpp.i

src/Gui/backends/imgui_impl_opengl3.s: src/Gui/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/Gui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
src/Gui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_opengl3.cpp.s
.PHONY : src/Gui/backends/imgui_impl_opengl3.cpp.s

src/Gui/backends/imgui_impl_sdl2.o: src/Gui/backends/imgui_impl_sdl2.cpp.o
.PHONY : src/Gui/backends/imgui_impl_sdl2.o

# target to build an object file
src/Gui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_sdl2.cpp.o
.PHONY : src/Gui/backends/imgui_impl_sdl2.cpp.o

src/Gui/backends/imgui_impl_sdl2.i: src/Gui/backends/imgui_impl_sdl2.cpp.i
.PHONY : src/Gui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
src/Gui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_sdl2.cpp.i
.PHONY : src/Gui/backends/imgui_impl_sdl2.cpp.i

src/Gui/backends/imgui_impl_sdl2.s: src/Gui/backends/imgui_impl_sdl2.cpp.s
.PHONY : src/Gui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
src/Gui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/backends/imgui_impl_sdl2.cpp.s
.PHONY : src/Gui/backends/imgui_impl_sdl2.cpp.s

src/Gui/imgui.o: src/Gui/imgui.cpp.o
.PHONY : src/Gui/imgui.o

# target to build an object file
src/Gui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui.cpp.o
.PHONY : src/Gui/imgui.cpp.o

src/Gui/imgui.i: src/Gui/imgui.cpp.i
.PHONY : src/Gui/imgui.i

# target to preprocess a source file
src/Gui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui.cpp.i
.PHONY : src/Gui/imgui.cpp.i

src/Gui/imgui.s: src/Gui/imgui.cpp.s
.PHONY : src/Gui/imgui.s

# target to generate assembly for a file
src/Gui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui.cpp.s
.PHONY : src/Gui/imgui.cpp.s

src/Gui/imgui_demo.o: src/Gui/imgui_demo.cpp.o
.PHONY : src/Gui/imgui_demo.o

# target to build an object file
src/Gui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_demo.cpp.o
.PHONY : src/Gui/imgui_demo.cpp.o

src/Gui/imgui_demo.i: src/Gui/imgui_demo.cpp.i
.PHONY : src/Gui/imgui_demo.i

# target to preprocess a source file
src/Gui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_demo.cpp.i
.PHONY : src/Gui/imgui_demo.cpp.i

src/Gui/imgui_demo.s: src/Gui/imgui_demo.cpp.s
.PHONY : src/Gui/imgui_demo.s

# target to generate assembly for a file
src/Gui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_demo.cpp.s
.PHONY : src/Gui/imgui_demo.cpp.s

src/Gui/imgui_draw.o: src/Gui/imgui_draw.cpp.o
.PHONY : src/Gui/imgui_draw.o

# target to build an object file
src/Gui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_draw.cpp.o
.PHONY : src/Gui/imgui_draw.cpp.o

src/Gui/imgui_draw.i: src/Gui/imgui_draw.cpp.i
.PHONY : src/Gui/imgui_draw.i

# target to preprocess a source file
src/Gui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_draw.cpp.i
.PHONY : src/Gui/imgui_draw.cpp.i

src/Gui/imgui_draw.s: src/Gui/imgui_draw.cpp.s
.PHONY : src/Gui/imgui_draw.s

# target to generate assembly for a file
src/Gui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_draw.cpp.s
.PHONY : src/Gui/imgui_draw.cpp.s

src/Gui/imgui_tables.o: src/Gui/imgui_tables.cpp.o
.PHONY : src/Gui/imgui_tables.o

# target to build an object file
src/Gui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_tables.cpp.o
.PHONY : src/Gui/imgui_tables.cpp.o

src/Gui/imgui_tables.i: src/Gui/imgui_tables.cpp.i
.PHONY : src/Gui/imgui_tables.i

# target to preprocess a source file
src/Gui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_tables.cpp.i
.PHONY : src/Gui/imgui_tables.cpp.i

src/Gui/imgui_tables.s: src/Gui/imgui_tables.cpp.s
.PHONY : src/Gui/imgui_tables.s

# target to generate assembly for a file
src/Gui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_tables.cpp.s
.PHONY : src/Gui/imgui_tables.cpp.s

src/Gui/imgui_widgets.o: src/Gui/imgui_widgets.cpp.o
.PHONY : src/Gui/imgui_widgets.o

# target to build an object file
src/Gui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_widgets.cpp.o
.PHONY : src/Gui/imgui_widgets.cpp.o

src/Gui/imgui_widgets.i: src/Gui/imgui_widgets.cpp.i
.PHONY : src/Gui/imgui_widgets.i

# target to preprocess a source file
src/Gui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_widgets.cpp.i
.PHONY : src/Gui/imgui_widgets.cpp.i

src/Gui/imgui_widgets.s: src/Gui/imgui_widgets.cpp.s
.PHONY : src/Gui/imgui_widgets.s

# target to generate assembly for a file
src/Gui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Gui/imgui_widgets.cpp.s
.PHONY : src/Gui/imgui_widgets.cpp.s

src/Particles.o: src/Particles.cpp.o
.PHONY : src/Particles.o

# target to build an object file
src/Particles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Particles.cpp.o
.PHONY : src/Particles.cpp.o

src/Particles.i: src/Particles.cpp.i
.PHONY : src/Particles.i

# target to preprocess a source file
src/Particles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Particles.cpp.i
.PHONY : src/Particles.cpp.i

src/Particles.s: src/Particles.cpp.s
.PHONY : src/Particles.s

# target to generate assembly for a file
src/Particles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Particles.cpp.s
.PHONY : src/Particles.cpp.s

src/Rectangle.o: src/Rectangle.cpp.o
.PHONY : src/Rectangle.o

# target to build an object file
src/Rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Rectangle.cpp.o
.PHONY : src/Rectangle.cpp.o

src/Rectangle.i: src/Rectangle.cpp.i
.PHONY : src/Rectangle.i

# target to preprocess a source file
src/Rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Rectangle.cpp.i
.PHONY : src/Rectangle.cpp.i

src/Rectangle.s: src/Rectangle.cpp.s
.PHONY : src/Rectangle.s

# target to generate assembly for a file
src/Rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Rectangle.cpp.s
.PHONY : src/Rectangle.cpp.s

src/RenderTarget.o: src/RenderTarget.cpp.o
.PHONY : src/RenderTarget.o

# target to build an object file
src/RenderTarget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/RenderTarget.cpp.o
.PHONY : src/RenderTarget.cpp.o

src/RenderTarget.i: src/RenderTarget.cpp.i
.PHONY : src/RenderTarget.i

# target to preprocess a source file
src/RenderTarget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/RenderTarget.cpp.i
.PHONY : src/RenderTarget.cpp.i

src/RenderTarget.s: src/RenderTarget.cpp.s
.PHONY : src/RenderTarget.s

# target to generate assembly for a file
src/RenderTarget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/RenderTarget.cpp.s
.PHONY : src/RenderTarget.cpp.s

src/Renderer.o: src/Renderer.cpp.o
.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Shader.o: src/Shader.cpp.o
.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Sprite.o: src/Sprite.cpp.o
.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i
.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s
.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/Text.o: src/Text.cpp.o
.PHONY : src/Text.o

# target to build an object file
src/Text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Text.cpp.o
.PHONY : src/Text.cpp.o

src/Text.i: src/Text.cpp.i
.PHONY : src/Text.i

# target to preprocess a source file
src/Text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Text.cpp.i
.PHONY : src/Text.cpp.i

src/Text.s: src/Text.cpp.s
.PHONY : src/Text.s

# target to generate assembly for a file
src/Text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Text.cpp.s
.PHONY : src/Text.cpp.s

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Transform.o: src/Transform.cpp.o
.PHONY : src/Transform.o

# target to build an object file
src/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Transform.cpp.o
.PHONY : src/Transform.cpp.o

src/Transform.i: src/Transform.cpp.i
.PHONY : src/Transform.i

# target to preprocess a source file
src/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Transform.cpp.i
.PHONY : src/Transform.cpp.i

src/Transform.s: src/Transform.cpp.s
.PHONY : src/Transform.s

# target to generate assembly for a file
src/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Transform.cpp.s
.PHONY : src/Transform.cpp.s

src/VertexArray.o: src/VertexArray.cpp.o
.PHONY : src/VertexArray.o

# target to build an object file
src/VertexArray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/VertexArray.cpp.o
.PHONY : src/VertexArray.cpp.o

src/VertexArray.i: src/VertexArray.cpp.i
.PHONY : src/VertexArray.i

# target to preprocess a source file
src/VertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/VertexArray.cpp.i
.PHONY : src/VertexArray.cpp.i

src/VertexArray.s: src/VertexArray.cpp.s
.PHONY : src/VertexArray.s

# target to generate assembly for a file
src/VertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/VertexArray.cpp.s
.PHONY : src/VertexArray.cpp.s

src/View.o: src/View.cpp.o
.PHONY : src/View.o

# target to build an object file
src/View.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/View.cpp.o
.PHONY : src/View.cpp.o

src/View.i: src/View.cpp.i
.PHONY : src/View.i

# target to preprocess a source file
src/View.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/View.cpp.i
.PHONY : src/View.cpp.i

src/View.s: src/View.cpp.s
.PHONY : src/View.s

# target to generate assembly for a file
src/View.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/View.cpp.s
.PHONY : src/View.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/renderer.dir/build.make CMakeFiles/renderer.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... uninstall"
	@echo "... Example"
	@echo "... SDL2-static"
	@echo "... SDL2_test"
	@echo "... SDL2main"
	@echo "... freetype"
	@echo "... glm"
	@echo "... renderer"
	@echo "... src/Batch.o"
	@echo "... src/Batch.i"
	@echo "... src/Batch.s"
	@echo "... src/Example/Application.o"
	@echo "... src/Example/Application.i"
	@echo "... src/Example/Application.s"
	@echo "... src/Example/ShaderUI.o"
	@echo "... src/Example/ShaderUI.i"
	@echo "... src/Example/ShaderUI.s"
	@echo "... src/Example/main.o"
	@echo "... src/Example/main.i"
	@echo "... src/Example/main.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/FrameBuffer.o"
	@echo "... src/FrameBuffer.i"
	@echo "... src/FrameBuffer.s"
	@echo "... src/Gui/backends/imgui_impl_opengl3.o"
	@echo "... src/Gui/backends/imgui_impl_opengl3.i"
	@echo "... src/Gui/backends/imgui_impl_opengl3.s"
	@echo "... src/Gui/backends/imgui_impl_sdl2.o"
	@echo "... src/Gui/backends/imgui_impl_sdl2.i"
	@echo "... src/Gui/backends/imgui_impl_sdl2.s"
	@echo "... src/Gui/imgui.o"
	@echo "... src/Gui/imgui.i"
	@echo "... src/Gui/imgui.s"
	@echo "... src/Gui/imgui_demo.o"
	@echo "... src/Gui/imgui_demo.i"
	@echo "... src/Gui/imgui_demo.s"
	@echo "... src/Gui/imgui_draw.o"
	@echo "... src/Gui/imgui_draw.i"
	@echo "... src/Gui/imgui_draw.s"
	@echo "... src/Gui/imgui_tables.o"
	@echo "... src/Gui/imgui_tables.i"
	@echo "... src/Gui/imgui_tables.s"
	@echo "... src/Gui/imgui_widgets.o"
	@echo "... src/Gui/imgui_widgets.i"
	@echo "... src/Gui/imgui_widgets.s"
	@echo "... src/Particles.o"
	@echo "... src/Particles.i"
	@echo "... src/Particles.s"
	@echo "... src/Rectangle.o"
	@echo "... src/Rectangle.i"
	@echo "... src/Rectangle.s"
	@echo "... src/RenderTarget.o"
	@echo "... src/RenderTarget.i"
	@echo "... src/RenderTarget.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/Text.o"
	@echo "... src/Text.i"
	@echo "... src/Text.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/Transform.o"
	@echo "... src/Transform.i"
	@echo "... src/Transform.s"
	@echo "... src/VertexArray.o"
	@echo "... src/VertexArray.i"
	@echo "... src/VertexArray.s"
	@echo "... src/View.o"
	@echo "... src/View.i"
	@echo "... src/View.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

